# Generated by Django 5.1.3 on 2025-01-26 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('permission_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('list', 'list (GET) - Retrieve a list of objects'), ('retrieve', 'retrieve (GET) - Retrieve a specific object by its ID'), ('create', 'create (POST) - Create a new object'), ('update', 'update (PUT/PATCH) - Update a specific object'), ('partial_update', 'partial_update (PATCH) - Partially update a specific object'), ('destroy', 'destroy (DELETE) - Delete a specific object')], max_length=20), blank=True, default=list, size=None)),
            ],
        ),
    ]
