# Generated by Django 5.1.4 on 2025-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='desk',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
