# Generated by Django 5.1.3 on 2025-01-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdownlog',
            name='problem_type',
        ),
        migrations.AddField(
            model_name='breakdownlog',
            name='problem_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_logs', to='maintenance.problemcategory'),
        ),
        migrations.DeleteModel(
            name='ProblemType',
        ),
    ]
