# Generated by Django 5.1.4 on 2025-01-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_machine_location_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
    ]
