# Generated by Django 5.1.3 on 2025-01-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_breakdownlog_repairing_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownlog',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_breakdowns', to='maintenance.machine'),
        ),
    ]
