# Generated by Django 5.1.4 on 2025-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_brand_slug_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
