# Generated by Django 5.1.4 on 2025-01-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_machine_id_alter_machine_machine_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
