# Generated by Django 5.1.4 on 2025-01-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_location_slug'),
        ('maintenance', '0005_delete_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('category_type', models.CharField(choices=[('machine', 'Machine Issue'), ('operator', 'Operator Error'), ('material', 'Material Defect'), ('environment', 'Environmental Issue')], default='machine', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='breakdownlog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.location'),
        ),
        migrations.AlterField(
            model_name='breakdownlog',
            name='problem_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='maintenance.problemcategory'),
        ),
    ]
