# Generated by Django 5.1.4 on 2025-01-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_problemcategory_breakdownlog_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownlog',
            name='problem_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='maintenance.problemcategory'),
        ),
    ]
