# Generated by Django 5.1.3 on 2024-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_machine_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_qr_codes/'),
        ),
    ]
