# Generated by Django 5.1.3 on 2024-11-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_machine_qr_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='qr_code_image',
        ),
    ]
